"use client";
import { useState } from "react";
import Link from "next/link";
type Project={id:string;name:string;version:number;updated_at:string}; type Overlay={project_id:string;public_id:string;enabled:boolean;requires_pro:boolean};
export function overlayDisplayState(overlay:Overlay|undefined,proAccess:boolean){if(!overlay)return "unpublished";if(!overlay.enabled)return "disabled";if(overlay.requires_pro&&!proAccess)return "inactive_subscription";return "active"}
export function DashboardClient({initialProjects,initialOverlays,plan,proAccess}:{initialProjects:Project[];initialOverlays:Overlay[];plan:string;proAccess:boolean}) {
 const [projects,setProjects]=useState(initialProjects),[overlays,setOverlays]=useState(initialOverlays),[busy,setBusy]=useState(false); const refresh=()=>fetch("/api/projects").then(r=>r.json()).then(d=>{setProjects(d.projects);setOverlays(d.overlays)});
 const create=async()=>{setBusy(true);const r=await fetch("/api/projects",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}),p=await r.json();setBusy(false);if(r.ok)location.href=`/editor?id=${p.id}`;else alert(p.message)};
 const act=async(p:Project,method:string,body?:object)=>{const r=await fetch(`/api/projects/${p.id}`,{method,headers:{"content-type":"application/json"},body:body?JSON.stringify({...body,version:p.version}):undefined});if(!r.ok){alert((await r.json()).message);return}await refresh()};
 const publish=async(id:string)=>{const r=await fetch("/api/overlays/publish",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId:id})});const d=await r.json();if(!r.ok)alert(d.message||d.error);else{await refresh();await navigator.clipboard.writeText(new URL(d.url,location.origin).href)}};
 const labels={active:"Overlay active",disabled:"Disabled by user",inactive_subscription:"Inactive because Pro expired",unpublished:"Not published"};
 return <><section className="dashboard-head"><div><p className="eyebrow">{plan.toUpperCase()} PLAN</p><h1>Your overlay projects</h1></div><button disabled={busy} onClick={create}>{busy?"Creating…":"Create project"}</button></section><div className="project-grid">{projects.map(p=>{const o=overlays.find(x=>x.project_id===p.id),status=overlayDisplayState(o,proAccess);return <article className="card" key={p.id}><h2>{p.name}</h2><p>Saved {new Date(p.updated_at).toLocaleString()} · v{p.version}</p><p className={status==="active"?"success":"muted"}>{labels[status]}</p><div className="actions"><Link className="button" href={`/editor?id=${p.id}`}>Open</Link><button onClick={()=>{const name=prompt("Project name",p.name);if(name)act(p,"PATCH",{name})}}>Rename</button><button onClick={()=>act(p,"PATCH",{action:"duplicate"})}>Duplicate</button><button onClick={()=>publish(p.id)}>Publish & copy URL</button>{o&&<button onClick={()=>fetch("/api/overlays/publish",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({projectId:p.id,enabled:!o.enabled})}).then(refresh)}>{o.enabled?"Disable":"Enable"}</button>}<button className="danger" onClick={()=>confirm("Delete this project?")&&act(p,"DELETE")}>Delete</button></div></article>})}</div></>;
}
