import {describe,expect,it} from "vitest";
import {defaultProject} from "@/lib/editor/defaults";
import {normalizeProject} from "@/lib/editor/normalization";
import {deserializeProject,serializeProject} from "@/lib/editor/serialization";
import {pushHistory,redoProject,undoProject} from "@/lib/editor/history";

describe("legacy parity data contract",()=>{
 it("creates plain UUID project IDs with approved editor defaults",()=>{const p=defaultProject();expect(p.id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i);expect(p.id.startsWith("project_")).toBe(false);expect(p.settings).toMatchObject({speed:5,theme:"themeNone",preview:"previewChecker"});expect(p.slides[0].layers[0]).toMatchObject({type:"text",x:50,y:82,fontSize:72,stroke:3})});
 it("preserves all legacy text, animation and unknown properties",()=>{const p=normalizeProject({name:"Legacy",version:7,slides:[{giftName:"Gift",animation:"animElectric",layers:[{type:"text",text:"A B\nC",effect:"aurora",textAnimation:"glitchLetters",textAnimationSpeed:.55,textLetterDelay:.025,textShimmer:true,textShimmerSpeed:1.7,boxEnabled:true,boxColor:"#123456",boxOpacity:44,boxRadius:9,boxPad:6,futureProperty:{kept:true}}]}]});expect(p.slides[0].entranceAnimation).toBe("animElectric");expect(p.slides[0].layers[0]).toMatchObject({effect:"aurora",textAnimation:"glitchLetters",textAnimationSpeed:.55,textLetterDelay:.025,textShimmer:true,boxEnabled:true,futureProperty:{kept:true}})});
 it("preserves legacy image crop, burst, particle and inner dimensions",()=>{const p=normalizeProject({slides:[{layers:[{type:"image",image:"data:image/png;base64,AA",imgW:67,imgH:81,fit:"cover",cropX:12,cropY:-9,cropZoom:155,imageAnimation:"imgRocketIn",imageAnimationSpeed:.85,burstEffect:"burstComet",burstSpeed:1.15,particle:"stars",particleSpeed:3.1}]}]});expect(p.slides[0].layers[0]).toMatchObject({type:"image",imageUrl:"data:image/png;base64,AA",imageWidth:67,imageHeight:81,fit:"cover",cropX:12,cropY:-9,cropZoom:155,imageAnimation:"imgRocketIn",burstEffect:"burstComet",particle:"stars"})});
 it("round-trips saving and loading without discarding legacy properties",()=>{const p=normalizeProject({slides:[{layers:[{type:"text",text:"Saved",effect:"goldText",textShimmer:true,unresolved:"retain"}]}]});expect(deserializeProject(serializeProject(p))).toEqual(p)});
 it("supports legacy top-level slide imports",()=>{const p=normalizeProject({slides:[{image:"data:image/png;base64,AA",fileName:"gift.png",imageX:31,imageY:42,text:"Thanks",textX:54,textY:88}]});expect(p.slides[0].layers).toHaveLength(2);expect(p.slides[0].layers[0]).toMatchObject({type:"image",x:31,y:42});expect(p.slides[0].layers[1]).toMatchObject({type:"text",text:"Thanks",x:54,y:88})});
 it("normalizes replacement IDs to the selected cloud UUID",()=>{const routeId=crypto.randomUUID(),imported=deserializeProject(JSON.stringify({id:"project_old",slides:[{layers:[{type:"text",text:"x"}]}]}));imported.id=routeId;expect(imported.id).toBe(routeId)});
 it("undoes and redoes legacy animation properties",()=>{const a=defaultProject(),past=pushHistory([],a),b=structuredClone(a);const text=b.slides[0].layers[0];if(text.type!=="text")throw new Error();text.textAnimation="waveLetters";const undone=undoProject(past,b,[]),redone=redoProject(undone.past,undone.current,undone.future);expect((undone.current.slides[0].layers[0] as {textAnimation:string}).textAnimation).toBe("none");expect((redone.current.slides[0].layers[0] as {textAnimation:string}).textAnimation).toBe("waveLetters")});
});
