import { describe, expect, it, vi } from "vitest";
import { safeNext } from "@/lib/http";
import { blocksCheckout } from "@/lib/billing/checkoutGuards";
import { SaveCoordinator } from "@/lib/projects/saveCoordinator";
import { defaultProject } from "@/lib/editor/defaults";
import { overlayDisplayState } from "@/components/dashboard/DashboardClient";
import { MAX_ENCODED_IMAGE_LENGTH, MAX_RAW_IMAGE_BYTES, projectSchema } from "@/lib/validation/projectSchemas";

describe("authentication redirect hardening",()=>{it.each([["/dashboard","/dashboard"],["/editor?id=123","/editor?id=123"],["//evil.example","/dashboard"],["/\\evil.example","/dashboard"],["/%5Cevil.example","/dashboard"],["https://evil.example","/dashboard"],["javascript:alert(1)","/dashboard"]])("validates %s",(candidate,expected)=>expect(safeNext(candidate)).toBe(expected))});
describe("checkout guard",()=>{it.each(["active","trialing","past_due"])("blocks %s",status=>expect(blocksCheckout({status})).toBe(true));it("blocks cancellation through paid period",()=>expect(blocksCheckout({status:"canceled",cancel_at_period_end:true,current_period_end:new Date(Date.now()+10000).toISOString()})).toBe(true))});
describe("save coordinator",()=>{it("serializes and persists the newest edit",async()=>{const resolvers:Array<(v:{version:number})=>void>=[],request=vi.fn(()=>new Promise<{version:number}>(resolve=>resolvers.push(resolve))),saved=vi.fn(),c=new SaveCoordinator(1,request,{saving:vi.fn(),saved,error:vi.fn()}),a=defaultProject(),b=structuredClone(a);b.name="B";const first=c.enqueue(a,1);c.enqueue(b,2);expect(request).toHaveBeenCalledTimes(1);resolvers[0]({version:2});await vi.waitFor(()=>expect(request).toHaveBeenCalledTimes(2));resolvers[1]({version:3});await first;expect(c.serverVersion).toBe(3);expect(saved).toHaveBeenLastCalledWith(2)});it("reconciles stale versions",async()=>{let n=0;const c=new SaveCoordinator(1,async()=>{if(!n++)throw Object.assign(new Error("stale"),{status:409,version:4});return{version:5}},{saving:vi.fn(),saved:vi.fn(),error:vi.fn()});await c.enqueue(defaultProject(),1);expect(c.serverVersion).toBe(5)})});
describe("overlay status",()=>{const base={project_id:"p",public_id:"x",enabled:true,requires_pro:false};it("reports all entitlement states",()=>{expect(overlayDisplayState(base,false)).toBe("active");expect(overlayDisplayState({...base,requires_pro:true},true)).toBe("active");expect(overlayDisplayState({...base,requires_pro:true},false)).toBe("inactive_subscription");expect(overlayDisplayState({...base,enabled:false},true)).toBe("disabled")})});
describe("encoded image boundary",()=>{it("keeps raw input below data URL expansion limit",()=>expect(Math.ceil(MAX_RAW_IMAGE_BYTES*4/3)+30).toBeLessThanOrEqual(MAX_ENCODED_IMAGE_LENGTH));it("rejects an encoded image over the limit",()=>{const p=defaultProject();p.slides[0].layers[0]={...p.slides[0].layers[0],type:"image",imageUrl:"x".repeat(MAX_ENCODED_IMAGE_LENGTH+1),fileName:"x",fit:"contain",cropX:0,cropY:0,cropZoom:1,imageWidth:1,imageHeight:1,outline:0,outlineColor:"#000",glow:0,glowColor:"#000"} as never;expect(projectSchema.safeParse(p).success).toBe(false)})});
