export type AnimationType = "none" | "wave" | "bounce-wave" | "pulse" | "glow-pulse" | "jitter" | "float" | "wiggle" | "bounce-loop" | "hover" | "shake" | "orbit" | "flip" | "waveLetters" | "bounceLetters" | "typewriterLetters" | "glitchLetters" | "flickerLetters" | "breatheText" | "imgPopBurst" | "imgImpactDrop" | "imgRocketIn" | "imgSpinSlam" | "imgFloatLoop" | "imgPulseLoop" | "imgWiggleLoop" | "imgSlowZoomIn" | "imgHoverBounce";
export interface LayerAnimationSettings { type: AnimationType; speed: number; intensity: number; delay: number }
export interface LayerBase { id:string; name:string; x:number; y:number; w:number; h:number; opacity:number; locked:boolean; animation:LayerAnimationSettings }
export interface TextLayer extends LayerBase { type:"text"; text:string; fontSize:number; effect:"solid"|"gradient"|"customGradient"|"rainbow"|"aurora"|"fireText"|"iceText"|"goldText"; color:string; gradient1:string; gradient2:string; gradientAngle:number; stroke:number; textAnimation:AnimationType; textAnimationSpeed:number; textLetterDelay:number; textShimmer:boolean; textShimmerSpeed:number; boxEnabled:boolean; boxColor:string; boxOpacity:number; boxRadius:number; boxPad:number; [key:string]:unknown }
export interface ImageLayer extends LayerBase { type:"image"; imageUrl:string; fileName:string; fit:"contain"|"cover"; cropX:number; cropY:number; cropZoom:number; imageWidth:number; imageHeight:number; outline:number; outlineColor:string; glow:number; glowColor:string; imageAnimation:AnimationType; imageAnimationSpeed:number; burstEffect:"none"|"burstImpact"|"burstRing"|"burstStar"|"burstComet"|"burstShockwave"|"burstLoop"; burstSpeed:number; particle:string; particleSpeed:number; [key:string]:unknown }
export type Layer = TextLayer | ImageLayer;
export type EntranceAnimation="none"|"animFade"|"animPop"|"animBounce"|"animSpin"|"animShake"|"animSlideUp"|"animFirePulse"|"animElectric"|"animZoomPunch"|"animGlitch"|"animSoftFloat";
export interface Slide { id:string; name:string; entranceAnimation:EntranceAnimation; duration:number; layers:Layer[]; [key:string]:unknown }
export interface EditorSettings { speed:number; theme:"themeNone"|"themeGlowBlueOrange"|"themeNeonGreenPurple"|"themeGoldVIP"|"themeFire"|"themeIce"; preview:"previewChecker"|"previewClear"|"previewBlack"|"previewGreen"; showCenter:boolean; showSafe:boolean }
export interface Project { id:string; name:string; schemaVersion:2; slides:Slide[]; settings:EditorSettings; updatedAt:string }
export interface EditorState { project:Project; currentSlideId:string; selectedLayerId:string|null; past:Project[]; future:Project[]; saveStatus:"saved"|"saving"|"dirty"|"error" }
export interface PublishedOverlay { publicId:string; ownerId:string; projectId:string; enabled:boolean; snapshot:Project|import("@/lib/overlays/legacy").LegacyPublishedSnapshot; publishedAt:string }
