import {z} from "zod";
export const MAX_ENCODED_IMAGE_LENGTH=8_000_000;
export const MAX_RAW_IMAGE_BYTES=5_999_970;
const animationType=z.enum(["none","wave","bounce-wave","pulse","glow-pulse","jitter","float","wiggle","bounce-loop","hover","shake","orbit","flip","waveLetters","bounceLetters","typewriterLetters","glitchLetters","flickerLetters","breatheText","imgPopBurst","imgImpactDrop","imgRocketIn","imgSpinSlam","imgFloatLoop","imgPulseLoop","imgWiggleLoop","imgSlowZoomIn","imgHoverBounce"]);
const animation=z.object({type:animationType,speed:z.number().min(.1).max(20),intensity:z.number().min(0).max(10),delay:z.number().min(0).max(60)}).passthrough();
const base={id:z.string().min(1),name:z.string().max(200),x:z.number(),y:z.number(),w:z.number().positive(),h:z.number().positive(),opacity:z.number().min(0).max(100),locked:z.boolean(),animation};
const text=z.object({...base,type:z.literal("text"),text:z.string().max(10000),fontSize:z.number(),effect:z.enum(["solid","gradient","customGradient","rainbow","aurora","fireText","iceText","goldText"]),color:z.string(),gradient1:z.string(),gradient2:z.string(),gradientAngle:z.number(),stroke:z.number(),textAnimation:animationType,textAnimationSpeed:z.number(),textLetterDelay:z.number(),textShimmer:z.boolean(),textShimmerSpeed:z.number(),boxEnabled:z.boolean(),boxColor:z.string(),boxOpacity:z.number(),boxRadius:z.number(),boxPad:z.number()}).passthrough();
const image=z.object({...base,type:z.literal("image"),imageUrl:z.string().max(MAX_ENCODED_IMAGE_LENGTH),fileName:z.string(),fit:z.enum(["contain","cover"]),cropX:z.number(),cropY:z.number(),cropZoom:z.number(),imageWidth:z.number(),imageHeight:z.number(),outline:z.number(),outlineColor:z.string(),glow:z.number(),glowColor:z.string(),imageAnimation:animationType,imageAnimationSpeed:z.number(),burstEffect:z.enum(["none","burstImpact","burstRing","burstStar","burstComet","burstShockwave","burstLoop"]),burstSpeed:z.number(),particle:z.string(),particleSpeed:z.number()}).passthrough();
export const projectSchema=z.object({id:z.string(),name:z.string().max(200),schemaVersion:z.literal(2),slides:z.array(z.object({id:z.string(),name:z.string(),entranceAnimation:z.enum(["none","animFade","animPop","animBounce","animSpin","animShake","animSlideUp","animFirePulse","animElectric","animZoomPunch","animGlitch","animSoftFloat"]),duration:z.number(),layers:z.array(z.discriminatedUnion("type",[text,image])).min(1)}).passthrough()).min(1).max(100),settings:z.object({speed:z.number(),theme:z.enum(["themeNone","themeGlowBlueOrange","themeNeonGreenPurple","themeGoldVIP","themeFire","themeIce"]),preview:z.enum(["previewChecker","previewClear","previewBlack","previewGreen"]),showCenter:z.boolean(),showSafe:z.boolean()}),updatedAt:z.string()}).passthrough();
