create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.projects (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, name text not null check(char_length(name)<=200), data jsonb not null, version integer not null default 1 check(version>0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists projects_owner_updated on public.projects(owner_id,updated_at desc);
create table if not exists public.overlays (id uuid primary key default gen_random_uuid(), public_id text not null unique check(char_length(public_id)>=20), owner_id uuid not null references auth.users(id) on delete cascade, project_id uuid not null unique references public.projects(id) on delete cascade, snapshot jsonb not null, enabled boolean not null default true, requires_pro boolean not null default false, published_at timestamptz not null default now(), version integer not null default 1);
create table if not exists public.subscriptions (user_id uuid primary key references auth.users(id) on delete cascade, stripe_customer_id text unique, stripe_subscription_id text unique, price_id text, status text not null default 'free', current_period_start timestamptz, current_period_end timestamptz, cancel_at_period_end boolean not null default false, canceled_at timestamptz, trial_end timestamptz, grace_period_end timestamptz, suspended boolean not null default false, last_event_created bigint not null default 0, updated_at timestamptz not null default now());
create table if not exists public.stripe_events (event_id text primary key, event_type text not null, created bigint not null, processed boolean not null default false, processed_at timestamptz, error text, received_at timestamptz not null default now());
create table if not exists public.assets (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, storage_path text not null unique, mime_type text not null, byte_size bigint not null check(byte_size between 1 and 8000000), created_at timestamptz not null default now());
alter table public.profiles enable row level security;alter table public.projects enable row level security;alter table public.overlays enable row level security;alter table public.subscriptions enable row level security;alter table public.stripe_events enable row level security;alter table public.assets enable row level security;
create policy "profiles select own" on public.profiles for select using(auth.uid()=id);create policy "profiles update own" on public.profiles for update using(auth.uid()=id) with check(auth.uid()=id);
create policy "projects select own" on public.projects for select using(auth.uid()=owner_id);create policy "projects insert own" on public.projects for insert with check(auth.uid()=owner_id);create policy "projects update own" on public.projects for update using(auth.uid()=owner_id) with check(auth.uid()=owner_id);create policy "projects delete own" on public.projects for delete using(auth.uid()=owner_id);
create policy "overlays select own" on public.overlays for select using(auth.uid()=owner_id);create policy "overlays insert own" on public.overlays for insert with check(auth.uid()=owner_id);create policy "overlays update own" on public.overlays for update using(auth.uid()=owner_id) with check(auth.uid()=owner_id);create policy "overlays delete own" on public.overlays for delete using(auth.uid()=owner_id);
create policy "subscriptions select own" on public.subscriptions for select using(auth.uid()=user_id);
create policy "assets select own" on public.assets for select using(auth.uid()=owner_id);create policy "assets insert own" on public.assets for insert with check(auth.uid()=owner_id);create policy "assets delete own" on public.assets for delete using(auth.uid()=owner_id);
-- No client policies exist for stripe_events or billing writes; service-role APIs are the sole writers.
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id) values(new.id) on conflict do nothing;return new;end$$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
