import { defaultAnimation, defaultImage, defaultProject, defaultSlide, defaultText } from "./defaults";
import type { AnimationType, EditorSettings, Layer, Project, Slide } from "@/types/editor";
import { normalizeProjectIdOrNew } from "@/lib/projects/projectIds";
const num=(v:unknown,f:number)=>typeof v==="number"&&Number.isFinite(v)?v:f;
const str=(v:unknown,f:string)=>typeof v==="string"?v:f;
const record=(v:unknown):Record<string,unknown>=>v&&typeof v==="object"?v as Record<string,unknown>:{};
const oneOf=<T extends string>(value:unknown, values:readonly T[], fallback:T):T =>
  typeof value === "string" && values.includes(value as T) ? value as T : fallback;
const animationTypes = ["none","wave","bounce-wave","pulse","glow-pulse","jitter","float","wiggle","bounce-loop","hover","shake","orbit","flip"] as const satisfies readonly AnimationType[];
const entranceAnimations = ["none","fade","slide-left","slide-right","zoom"] as const satisfies readonly Slide["entranceAnimation"][];

export function normalizeLayer(input:unknown):Layer { const l=record(input); const a=record(l.animation); const animation={...defaultAnimation(),type:oneOf(a.type??l.textAnimation??l.imageAnimation,animationTypes,"none"),speed:num(a.speed,num(l.textAnimationSpeed??l.imageAnimationSpeed,1)),intensity:num(a.intensity,1),delay:num(a.delay,num(l.textLetterDelay,0))}; const common={id:str(l.id,crypto.randomUUID()),name:str(l.name,"Layer"),x:num(l.x,50),y:num(l.y,50),w:Math.max(1,num(l.w,28)),h:Math.max(1,num(l.h,28)),opacity:num(l.opacity,100),locked:Boolean(l.locked),animation}; if(l.type==="image"){const d=defaultImage(str(l.imageUrl??l.image,""),str(l.fileName,"Image")); return {...d,...common,type:"image",imageUrl:str(l.imageUrl??l.image,""),fileName:str(l.fileName,""),fit:l.fit==="cover"?"cover":"contain",cropX:num(l.cropX,0),cropY:num(l.cropY,0),cropZoom:num(l.cropZoom,100),imageWidth:num(l.imageWidth??l.imgW,common.w),imageHeight:num(l.imageHeight??l.imgH,common.h),outline:num(l.outline,0),outlineColor:str(l.outlineColor,"#ffffff"),glow:num(l.glow,0),glowColor:str(l.glowColor,"#00aaff")};} const d=defaultText(); return {...d,...common,type:"text",text:str(l.text,"New Text"),fontSize:num(l.fontSize,72),effect:l.effect==="gradient"||l.effect==="customGradient"?"gradient":"solid",color:str(l.color,"#57fff4"),gradient1:str(l.gradient1,"#00aaff"),gradient2:str(l.gradient2,"#ff7a00"),gradientAngle:num(l.gradientAngle,90),stroke:num(l.stroke,3)}; }
export function normalizeSlide(input:unknown):Slide {const s=record(input);const layers=Array.isArray(s.layers)?s.layers.map(normalizeLayer):[];const d=defaultSlide();return{...d,id:str(s.id,d.id),name:str(s.name??s.giftName,"New Gift"),entranceAnimation:oneOf(s.entranceAnimation??s.animation,entranceAnimations,"none"),duration:num(s.duration,0),layers:layers.length?layers:[defaultText()]};}
export function normalizeProject(input:unknown):Project {const p=record(input);const d=defaultProject();const slides=Array.isArray(p.slides)?p.slides.map(normalizeSlide):d.slides;const settings=record(p.settings);const normalizedSettings:EditorSettings={speed:Math.max(0.1,num(settings.speed,d.settings.speed)),theme:oneOf(settings.theme,["none","neon","glass"],d.settings.theme),preview:oneOf(settings.preview,["checker","clear","black","green"],d.settings.preview),showCenter:typeof settings.showCenter==="boolean"?settings.showCenter:d.settings.showCenter,showSafe:typeof settings.showSafe==="boolean"?settings.showSafe:d.settings.showSafe};return{...d,id:normalizeProjectIdOrNew(p.id),name:str(p.name,"Untitled Overlay"),slides:slides.length?slides:d.slides,settings:normalizedSettings,schemaVersion:2,updatedAt:str(p.updatedAt,new Date().toISOString())};}
